"""
Model: activation_code. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""
from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import Boolean, ForeignKey, ForeignKeyConstraint, Index, Integer, String, Text, text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base


class ActivationCode(Base):
    __tablename__ = 'activation_code'
    __table_args__ = (
        ForeignKeyConstraint(['used_by_user_id'], ['user.id'], ondelete='SET NULL', name='fk_activation_code_used_by_user_id'),
        Index('fk_activation_code_used_by_user_id', 'used_by_user_id'),
        Index('idx_code', 'code', unique=True),
        Index('idx_created_at', 'created_at'),
        Index('idx_deleted_at', 'deleted_at'),
        Index('idx_updated_at', 'updated_at')
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    code: Mapped[str] = mapped_column(String(32, 'utf8mb4_unicode_ci'), nullable=False)
    status: Mapped[str] = mapped_column(String(16, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'unused'"))
    created_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6)'))
    updated_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    used_by_user_id: Mapped[Optional[int]] = mapped_column(BIGINT)
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    used_by_user: Mapped[Optional["User"]] = relationship("User", back_populates="activation_code")  # type: ignore[name-defined]

__all__ = ["ActivationCode"]
