"""
Model: subtitle_line. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""

from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.mysql import BIGINT, DATETIME
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base


class SubtitleLine(Base):
    __tablename__ = "subtitle_line"
    __table_args__ = (
        ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            ondelete="CASCADE",
            name="fk_subtitle_line_video_id",
        ),
        Index("idx_created_at", "created_at"),
        Index("idx_deleted_at", "deleted_at"),
        Index("idx_language", "language"),
        Index("idx_updated_at", "updated_at"),
        Index("idx_video_id", "video_id"),
        Index("idx_video_id_start_ms", "video_id", "start_ms"),
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    video_id: Mapped[int] = mapped_column(BIGINT, nullable=False)
    start_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    end_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    language: Mapped[str] = mapped_column(
        String(16, "utf8mb4_unicode_ci"), nullable=False
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DATETIME(fsp=6), nullable=False, server_default=text("CURRENT_TIMESTAMP(6)")
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DATETIME(fsp=6),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
    )
    content: Mapped[Optional[str]] = mapped_column(Text(collation="utf8mb4_unicode_ci"))
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    video: Mapped["Video"] = relationship("Video", back_populates="subtitle_line")  # type: ignore[name-defined]
    user_sentence: Mapped[list["UserSentence"]] = relationship(
        "UserSentence", back_populates="subtitle_line"
    )  # type: ignore[name-defined]
    user_vocabulary: Mapped[list["UserVocabulary"]] = relationship(
        "UserVocabulary", back_populates="source_subtitle"
    )  # type: ignore[name-defined]


__all__ = ["SubtitleLine"]
