"""
Model: user_device. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""
from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import Boolean, ForeignKey, ForeignKeyConstraint, Index, Integer, String, Text, text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base


class UserDevice(Base):
    __tablename__ = 'user_device'
    __table_args__ = (
        ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE', name='fk_user_device_user_id'),
        Index('idx_created_at', 'created_at'),
        Index('idx_deleted_at', 'deleted_at'),
        Index('idx_updated_at', 'updated_at'),
        Index('idx_user_id', 'user_id')
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    user_id: Mapped[int] = mapped_column(BIGINT, nullable=False)
    device_id: Mapped[str] = mapped_column(String(128, 'utf8mb4_unicode_ci'), nullable=False)
    device_name: Mapped[str] = mapped_column(String(64, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    last_active_at: Mapped[str] = mapped_column(String(32, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    status: Mapped[str] = mapped_column(String(16, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'active'"))  # 'active' | 'logged_out'
    created_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6)'))
    updated_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    user: Mapped["User"] = relationship("User", back_populates="user_device")  # type: ignore[name-defined]

__all__ = ["UserDevice"]
