"""
Model: user. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""

from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.mysql import BIGINT, DATETIME, TINYINT
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base


class User(Base):
    __tablename__ = "user"
    __table_args__ = (
        Index("idx_created_at", "created_at"),
        Index("idx_deleted_at", "deleted_at"),
        Index("idx_email", "email", unique=True),
        Index("idx_phone", "phone", unique=True),
        Index("idx_updated_at", "updated_at"),
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    password_hash: Mapped[str] = mapped_column(
        String(255, "utf8mb4_unicode_ci"), nullable=False
    )
    password_salt: Mapped[Optional[str]] = mapped_column(
        String(64, "utf8mb4_unicode_ci"), nullable=True
    )
    is_active: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'1'")
    )
    level: Mapped[str] = mapped_column(
        String(32, "utf8mb4_unicode_ci"), nullable=False, server_default=text("'free'")
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DATETIME(fsp=6), nullable=False, server_default=text("CURRENT_TIMESTAMP(6)")
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DATETIME(fsp=6),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
    )
    phone: Mapped[Optional[str]] = mapped_column(String(32, "utf8mb4_unicode_ci"))
    email: Mapped[Optional[str]] = mapped_column(String(255, "utf8mb4_unicode_ci"))
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    activation_code: Mapped[list["ActivationCode"]] = relationship(
        "ActivationCode", back_populates="used_by_user"
    )  # type: ignore[name-defined]
    user_device: Mapped[list["UserDevice"]] = relationship(
        "UserDevice", back_populates="user"
    )  # type: ignore[name-defined]
    user_sentence: Mapped[list["UserSentence"]] = relationship(
        "UserSentence", back_populates="user"
    )  # type: ignore[name-defined]
    user_vocabulary: Mapped[list["UserVocabulary"]] = relationship(
        "UserVocabulary", back_populates="user"
    )  # type: ignore[name-defined]


__all__ = ["User"]
