"""
Model: user_vocabulary. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""
from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import Boolean, ForeignKey, ForeignKeyConstraint, Index, Integer, String, Text, text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base

class UserVocabulary(Base):
    __tablename__ = 'user_vocabulary'
    __table_args__ = (
        ForeignKeyConstraint(['source_subtitle_id'], ['subtitle_line.id'], ondelete='SET NULL', name='fk_user_vocabulary_source_subtitle_id'),
        ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE', name='fk_user_vocabulary_user_id'),
        Index('fk_user_vocabulary_source_subtitle_id', 'source_subtitle_id'),
        Index('idx_created_at', 'created_at'),
        Index('idx_deleted_at', 'deleted_at'),
        Index('idx_updated_at', 'updated_at'),
        Index('idx_user_id', 'user_id')
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    user_id: Mapped[int] = mapped_column(BIGINT, nullable=False)
    word: Mapped[str] = mapped_column(String(128, 'utf8mb4_unicode_ci'), nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6)'))
    updated_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    definition: Mapped[Optional[str]] = mapped_column(Text(collation='utf8mb4_unicode_ci'))
    source_subtitle_id: Mapped[Optional[int]] = mapped_column(BIGINT)
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    source_subtitle: Mapped[Optional["SubtitleLine"]] = relationship("SubtitleLine", back_populates="user_vocabulary")  # type: ignore[name-defined]
    user: Mapped["User"] = relationship("User", back_populates="user_vocabulary")  # type: ignore[name-defined]

__all__ = ["UserVocabulary"]
