"""
Model: video. Generated by scripts/gen_models_from_db.py. Do not edit by hand.
Regenerate: python scripts/gen_models_from_db.py
"""
from __future__ import annotations

import datetime
from typing import Optional

from sqlalchemy import Boolean, ForeignKey, ForeignKeyConstraint, Index, Integer, String, Text, text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.utils.id_generator import generate_bigint_id
from .base import Base


class Video(Base):
    __tablename__ = 'video'
    __table_args__ = (
        Index('idx_created_at', 'created_at'),
        Index('idx_deleted_at', 'deleted_at'),
        Index('idx_external_id', 'external_id', unique=True),
        Index('idx_updated_at', 'updated_at')
    )

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    title_en: Mapped[str] = mapped_column(String(512, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    title_zh: Mapped[str] = mapped_column(String(512, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    thumbnail_url: Mapped[str] = mapped_column(String(1024, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    duration_seconds: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'0'"))
    difficulty: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("'1'"))
    accent: Mapped[str] = mapped_column(String(32, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'american'"))
    topic: Mapped[str] = mapped_column(String(64, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("''"))
    created_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6)'))
    updated_at: Mapped[datetime.datetime] = mapped_column(DATETIME(fsp=6), nullable=False, server_default=text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    external_id: Mapped[Optional[str]] = mapped_column(String(64, 'utf8mb4_unicode_ci'))
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(DATETIME(fsp=6))

    subtitle_line: Mapped[list["SubtitleLine"]] = relationship("SubtitleLine", back_populates="video")  # type: ignore[name-defined]

__all__ = ["Video"]
